export enum ProductCategory {
  Vegetables = 'Vegetables',
  Fruits = 'Fruits',
  Dairy = 'Dairy',
  Meats = 'Meats',
  Fishes = 'Fishes',
  Seafoods = 'Seafoods',
  DairyAlternatives = 'DairyAlternatives',
  DairyAndMeatAlternatives = 'DairyAndMeatAlternatives',
  BakingAndGrains = 'BakingAndGrains',
  Legumes = 'Legumes',
  Nuts = 'Nuts',
  Spices = 'Spices',
  Oils = 'Oils',
  Sauces = 'Sauces',
  Beverages = 'Beverages',
  Alcohol = 'Alcohol',
  DessertsAndSnacks = 'DessertsAndSnacks',
  FoodAdditives = 'FoodAdditives',
  Sweeteners = 'Sweeteners',
  Others = 'Others'
}
