export default {
  ERROR: 'ERROR',
  TOO_FREQUENT: 'TOO_FREQUENT',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  WRONG_PASSWORD_COMBINATION: 'WRONG_PASSWORD_COMBINATION',
  WRONG_USER_PASSWORD_COMBINATION: 'WRONG_USER_PASSWORD_COMBINATION',
  EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
  REQUIRED: 'REQUIRED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  REQUIRED_AT_LEAST_6_CHAR: 'REQUIRED_AT_LEAST_6_CHAR',
  REQUIRED_AT_LEAST_ONE_LOWER: 'REQUIRED_AT_LEAST_ONE_LOWER',
  REQUIRED_AT_LEAST_ONE_UPPER: 'REQUIRED_AT_LEAST_ONE_UPPER',
  REQUIRED_AT_LEAST_ONE_DIGIT: 'REQUIRED_AT_LEAST_ONE_DIGIT',
  REQUIRED_AT_LEAST_ONE_NON_ALPHANUM: 'REQUIRED_AT_LEAST_ONE_NON_ALPHANUM'
}
