name: Deploy to staging

on:
  push:
    branches: [ main, deploy-manual ]
  workflow_dispatch:


concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # will be ignored later
        known_hosts: placeholder
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Deploy with ssh
      run: |
        ssh -T ubuntu@${{ secrets.SSH_HOST }} <<EOF
        export GITHUB_BRANCH="${GITHUB_REF#refs/heads/}"
        export GITHUB_SHA="$GITHUB_SHA"
        $(cat ./scripts/deploy.sh)
        EOF

